package Service;

import Model.Person;
import Result.FillResult;

/**
 * A service to handle filling a user's and his/her family information
 */
public class FillService {

    /**
     * Fill in the data generated by a certain username
     * @param username pass in a Fill request
     * @return a Fill Result
     */
    public FillResult fill(String username){
        return null;
    }

    // generate data based on a username
    // @param pass in a username
    // @return a person
    public Person generateData(String username){
        return null;
    }

}
